version: '3.4'

services:
  node:
    build: 
     context: grpcCrud
    image: grpc-crud-users
    environment:
      PORT: 3000
      MONGODB_URL: mongodb://mongodb:27017/SUCHANA
      GRPC_HOST: 127.0.0.1

    ports:
      - '3000:3000'

    depends_on:
      - mongodb

    networks:
    - node-network

  mongodb:

    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - node-network

  client:
    image: web-app-client-users
    build:
      context: client
    
    environment:
      PORT: 3001
      portFromGrpc: 3000
    ports:
      - '3001:3001'
    
    networks:
      - node-network
volumes:
  dbdata6:

networks:
  node-network:
    driver: bridge